name: Waka Readme

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          REPOSITORY: Siris2314/Siris2314

          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ░▒▓█
          CODE_LANG: txt

          TIME_RANGE: last_7_days

          SHOW_TIME: false
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: false

          STOP_AT_OTHER: false
